# Generated by Django 3.0.3 on 2020-05-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPublicado',
            fields=[
                ('ide_formulario_publicado', models.AutoField(primary_key=True, serialize=False)),
                ('ide_usuario', models.TextField()),
                ('tex_url_formulario_publicado', models.TextField()),
                ('nom_titulo_formulario_publicado', models.TextField()),
                ('des_formulario_publicado', models.TextField(blank=True, null=True)),
                ('cod_tipo', models.TextField()),
                ('cod_divulgacao', models.TextField()),
                ('dat_publicacao', models.DateTimeField()),
                ('dat_inicio_vigencia', models.DateTimeField()),
                ('dat_fim_vigencia', models.DateTimeField(blank=True, null=True)),
                ('ind_permite_varias_respostas', models.TextField(blank=True, null=True)),
                ('des_conteudo', models.TextField()),
                ('des_informacao_adicional_1', models.TextField(blank=True, null=True)),
                ('des_informacao_adicional_2', models.TextField(blank=True, null=True)),
                ('des_informacao_adicional_3', models.TextField(blank=True, null=True)),
                ('des_url_post', models.TextField(blank=True, null=True)),
                ('ind_enquete_automatica', models.TextField(blank=True, null=True)),
                ('ind_enquete_com_posicionamentos', models.TextField(blank=True, null=True)),
                ('tex_url_link_externo', models.TextField(blank=True, null=True)),
                ('tex_label_link_externo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Formulario_Publicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemResposta',
            fields=[
                ('ide_item_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('num_indice_campo', models.IntegerField()),
                ('num_indice_opcao', models.IntegerField(blank=True, null=True)),
                ('num_indice_linha_tabela', models.IntegerField(blank=True, null=True)),
                ('tex_texto_livre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Item_Resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('ide_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('ide_usuario', models.TextField()),
                ('dat_resposta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('partido', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('situacao_descricao', models.TextField(blank=True, null=True)),
                ('situacao_data', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ManyToManyField(null=True, related_name='autor_set', to='enquetes.Deputado')),
                ('formulario_publicado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.FormularioPublicado')),
                ('relator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relator', to='enquetes.Deputado')),
            ],
        ),
    ]
