# Generated by Django 3.0.6 on 2020-05-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('partido', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPublicado',
            fields=[
                ('ide_formulario_publicado', models.AutoField(primary_key=True, serialize=False)),
                ('ide_usuario', models.TextField()),
                ('tex_url_formulario_publicado', models.TextField()),
                ('nom_titulo_formulario_publicado', models.TextField()),
                ('des_formulario_publicado', models.TextField(blank=True, null=True)),
                ('cod_tipo', models.TextField()),
                ('cod_divulgacao', models.TextField()),
                ('dat_publicacao', models.DateTimeField()),
                ('dat_inicio_vigencia', models.DateTimeField()),
                ('dat_fim_vigencia', models.DateTimeField(blank=True, null=True)),
                ('ind_permite_varias_respostas', models.TextField(blank=True, null=True)),
                ('des_conteudo', models.TextField()),
                ('des_informacao_adicional_1', models.TextField(blank=True, null=True)),
                ('des_informacao_adicional_2', models.TextField(blank=True, null=True)),
                ('des_informacao_adicional_3', models.TextField(blank=True, null=True)),
                ('des_url_post', models.TextField(blank=True, null=True)),
                ('ind_enquete_automatica', models.TextField(blank=True, null=True)),
                ('ind_enquete_com_posicionamentos', models.TextField(blank=True, null=True)),
                ('tex_url_link_externo', models.TextField(blank=True, null=True)),
                ('tex_label_link_externo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Formulario_Publicado',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.TextField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_tipo', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('ementa_detalhada', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('data_apresentacao', models.DateField(blank=True, null=True)),
                ('uri_prop_anterior', models.TextField(blank=True, null=True)),
                ('uri_prop_principal', models.TextField(blank=True, null=True)),
                ('uri_prop_posterior', models.TextField(blank=True, null=True)),
                ('url_inteiro_teor', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ultimo_status_situacao_descricao', models.TextField(blank=True, null=True)),
                ('ultimo_status_data', models.DateField(blank=True, null=True)),
                ('ultimo_status_descricao_situacao', models.TextField(blank=True, null=True)),
                ('autor', models.ManyToManyField(related_name='autor_set', to='enquetes.Deputado')),
                ('formulario_publicado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.FormularioPublicado')),
                ('orgao_numerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_numerador', to='enquetes.Orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('ide_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('ide_usuario', models.TextField()),
                ('dat_resposta', models.DateTimeField(blank=True, null=True)),
                ('ide_formulario_publicado', models.ForeignKey(db_column='ide_formulario_publicado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.FormularioPublicado')),
            ],
            options={
                'db_table': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='ProposicaoPageview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pageviews', models.IntegerField()),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.Proposicao')),
            ],
        ),
        migrations.AddField(
            model_name='proposicao',
            name='tema',
            field=models.ManyToManyField(to='enquetes.Tema'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='ultimo_status_orgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.Orgao'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='ultimo_status_relator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimo_status_relator', to='enquetes.Deputado'),
        ),
        migrations.CreateModel(
            name='ItemResposta',
            fields=[
                ('ide_item_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('num_indice_campo', models.IntegerField()),
                ('num_indice_opcao', models.IntegerField(blank=True, null=True)),
                ('num_indice_linha_tabela', models.IntegerField(blank=True, null=True)),
                ('tex_texto_livre', models.TextField(blank=True, null=True)),
                ('resposta', models.ForeignKey(db_column='ide_resposta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.Resposta')),
            ],
            options={
                'db_table': 'Item_Resposta',
            },
        ),
    ]
