# Generated by Django 3.0.3 on 2020-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='autor',
            field=models.ManyToManyField(related_name='autor_set', to='enquetes.Deputado'),
        ),
    ]
