# Generated by Django 3.0.3 on 2020-05-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_remove_proposta_formulario_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='formulario_publicado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.FormularioPublicado'),
        ),
    ]
