# Generated by Django 3.0.3 on 2020-05-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0004_proposta_formulario_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.TextField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_tipo', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('ementa_detalhada', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('data_apresentacao', models.TextField(blank=True, null=True)),
                ('prop_anterior_id', models.IntegerField(blank=True, null=True)),
                ('prop_principal_id', models.IntegerField(blank=True, null=True)),
                ('prop_posterior_id', models.IntegerField(blank=True, null=True)),
                ('url_inteiro_teor', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('situacao_descricao', models.TextField(blank=True, null=True)),
                ('situacao_data', models.DateTimeField(blank=True, null=True)),
                ('ultimo_status_data', models.DateTimeField(blank=True, null=True)),
                ('ultimo_status_descricao_situacao', models.TextField(blank=True, null=True)),
                ('autor', models.ManyToManyField(related_name='autor_set', to='enquetes.Deputado')),
                ('formulario_publicado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.FormularioPublicado')),
                ('orgao_numerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_numerador', to='enquetes.Orgao')),
                ('relator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relator', to='enquetes.Deputado')),
                ('ultimo_status_orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.Orgao')),
                ('ultimo_status_relator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimo_status_relator', to='enquetes.Deputado')),
            ],
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
