# Generated by Django 3.0.3 on 2020-05-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_auto_20200515_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposicao',
            old_name='situacao_descricao',
            new_name='ultimo_status_situacao_descricao',
        ),
        migrations.RenameField(
            model_name='proposicao',
            old_name='prop_anterior_id',
            new_name='uri_prop_anterior',
        ),
        migrations.RenameField(
            model_name='proposicao',
            old_name='prop_posterior_id',
            new_name='uri_prop_posterior',
        ),
        migrations.RenameField(
            model_name='proposicao',
            old_name='prop_principal_id',
            new_name='uri_prop_principal',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='situacao_data',
        ),
    ]
