# Generated by Django 3.0.3 on 2020-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0006_auto_20200515_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='uri_prop_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='uri_prop_posterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='uri_prop_principal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
