# Generated by Django 3.0.3 on 2020-05-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0007_auto_20200515_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposicao',
            name='relator',
        ),
    ]
