# Generated by Django 3.0.3 on 2020-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0008_remove_proposicao_relator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='ultimo_status_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
