# Generated by Django 3.0.3 on 2020-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0009_auto_20200515_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proposicao',
            name='tema',
            field=models.ManyToManyField(to='enquetes.Tema'),
        ),
    ]
