# Generated by Django 3.0.3 on 2020-05-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0010_auto_20200516_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='tema',
            new_name='nome',
        ),
    ]
