version: "3"

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:50101
    volumes:
      - .:/usr/src/app/
      - static_data:/usr/src/app/core/static
    ports:
      - 50101:50101
    entrypoint: /usr/src/app/conf/entrypoint.sh
    env_file:
      - ./conf/.env_docker
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./conf/.env_docker
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./conf/.env_docker
    depends_on:
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=camaraparticipacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx
    ports:
      - 50001:80
    volumes:
      - ./conf/nginx_conf:/etc/nginx/conf.d/default.conf
      - static_data:/home/app/web/project/static
    depends_on:
      - web

volumes:
  static_data:
  postgres_data:
    driver: local
