version: "3"

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:80
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:80
    entrypoint: /usr/src/app/entrypoint.sh
    env_file:
      - ./.env_docker
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./.env_docker
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./.env_docker
    depends_on:
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=camaraparticipacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
    driver: local 