version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:50101
    volumes:
      - .:/usr/src/app/
      - static_data:/usr/src/app/static
      - db_dump:/usr/src/app/db_dump
    ports:
      - 50101:50101
      - 4444:4444
    stdin_open: true
    tty: true
    entrypoint: /usr/src/app/conf/entrypoint.sh
    env_file:
      - ./conf/.env_docker
    depends_on:
      - db
      - celery
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./conf/.env_docker
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info --pidfile=
    volumes:
      - .:/usr/src/app/
    env_file:
    - ./conf/.env_docker
    depends_on:
      - redis
      - celery
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=camaraparticipacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    shm_size: 1g
  nginx:
    image: nginx
    ports:
      - 50001:80
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/home/app/web/project/static
    depends_on:
      - web

volumes:
  db_dump:
  static_data:
  postgres_data:
    driver: local
