version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:80
    depends_on:
      - db
    # env_file:
    #   - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: