# Generated by Django 3.0.6 on 2020-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariopublicado',
            name='tex_url_formulario_publicado',
            field=models.TextField(db_index=True),
        ),
    ]
