# Generated by Django 3.0.6 on 2020-05-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200520_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemresposta',
            old_name='resposta',
            new_name='ide_resposta',
        ),
        migrations.CreateModel(
            name='Posicionamento',
            fields=[
                ('ide_posicionamento', models.AutoField(primary_key=True, serialize=False)),
                ('ide_usuario', models.TextField(blank=True, null=True)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('ind_positivo', models.IntegerField()),
                ('qtd_curtidas', models.IntegerField()),
                ('des_conteudo', models.TextField(blank=True, null=True)),
                ('dat_posicionamento', models.DateTimeField(blank=True, null=True)),
                ('cod_autorizado', models.IntegerField(null=True)),
                ('qtd_descurtidas', models.IntegerField(null=True)),
                ('ide_formulario_publicado', models.ForeignKey(db_column='ide_formulario_publicado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.FormularioPublicado')),
                ('ide_resposta', models.ForeignKey(db_column='ide_resposta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Resposta')),
            ],
            options={
                'db_table': 'Posicionamento',
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide_usuario', models.TextField(blank=True, null=True)),
                ('ind_positivo', models.IntegerField(null=True)),
                ('ide_formulario_publicado', models.ForeignKey(db_column='ide_formulario_publicado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.FormularioPublicado')),
                ('ide_posicionamento', models.ForeignKey(db_column='ide_posicionamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Posicionamento')),
            ],
            options={
                'db_table': 'Curtida',
            },
        ),
    ]
