# Generated by Django 3.0.6 on 2020-05-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200524_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionamentoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(0, 'Unrated'), (1, 'Insightful'), (-1, 'Not insightful')], default=0)),
                ('posicionamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Posicionamento')),
            ],
        ),
    ]
