# Generated by Django 3.0.6 on 2020-07-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200606_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curtida',
        ),
    ]
