# Generated by Django 3.0.6 on 2020-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputado',
            name='nome_processado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='nome_processado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
