# Generated by Django 3.0.6 on 2020-07-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200723_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposicao',
            name='ultimo_status_descricao_situacao',
        ),
    ]
