# Generated by Django 3.0.6 on 2020-07-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_proposicao_ultimo_status_descricao_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('deputados', models.ManyToManyField(to='app.Deputado')),
                ('proposicoes', models.ManyToManyField(to='app.Proposicao')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProposicaoPageview',
            new_name='ProposicaoFichaPageviews',
        ),
        migrations.RenameField(
            model_name='proposicaoaggregated',
            old_name='pageviews',
            new_name='ficha_pageviews',
        ),
        migrations.AddField(
            model_name='proposicaoaggregated',
            name='noticia_pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NoticiaPageviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pageviews', models.IntegerField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noticia')),
            ],
        ),
    ]
