# Generated by Django 3.0.6 on 2020-07-29 00:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200727_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
