# Generated by Django 3.0.6 on 2020-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200805_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='autor',
            field=models.ManyToManyField(to='app.Autor'),
        ),
    ]
