# Generated by Django 3.0.6 on 2020-08-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicaoaggregated',
            name='poll_comments_authorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposicaoaggregated',
            name='poll_comments_checked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposicaoaggregated',
            name='poll_comments_unauthorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposicaoaggregated',
            name='poll_comments_unchecked',
            field=models.IntegerField(default=0),
        ),
    ]
