# Generated by Django 3.0.6 on 2020-12-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200818_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularioPublicado',
            new_name='EnqueteFormularioPublicado',
        ),
        migrations.RenameModel(
            old_name='ItemResposta',
            new_name='EnqueteItemResposta',
        ),
        migrations.RenameModel(
            old_name='Posicionamento',
            new_name='EnquetePosicionamento',
        ),
        migrations.RenameModel(
            old_name='PosicionamentoExtra',
            new_name='EnquetePosicionamentoExtra',
        ),
        migrations.RenameModel(
            old_name='Resposta',
            new_name='EnqueteResposta',
        ),
        migrations.AlterModelTable(
            name='enqueteformulariopublicado',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enqueteitemresposta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enqueteposicionamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='enqueteresposta',
            table=None,
        ),
    ]
