# Generated by Django 3.0.6 on 2020-12-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201214_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalComentario',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('usuario_id', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrismaDemandante',
            fields=[
                ('iddemandante', models.AutoField(db_column='IdDemandante', primary_key=True, serialize=False)),
                ('demandante_data_cadastro', models.DateTimeField(db_column='Demandante.Data Cadastro')),
                ('demandante_grau_de_instrução', models.TextField(blank=True, db_column='Demandante.Grau de Instrução', null=True)),
                ('demandante_sexo', models.TextField(blank=True, db_column='Demandante.Sexo', null=True)),
                ('demandante_categoria', models.TextField(blank=True, db_column='Demandante.Categoria', null=True)),
                ('demandante_data_de_nascimento', models.DateField(blank=True, db_column='Demandante.Data de Nascimento', null=True)),
                ('demandante_profissão_externa', models.TextField(blank=True, db_column='Demandante.Profissão Externa', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrismaDemanda',
            fields=[
                ('iddemanda', models.AutoField(db_column='IdDemanda', primary_key=True, serialize=False)),
                ('demanda_protocolo', models.TextField(blank=True, db_column='Demanda.Protocolo', null=True)),
                ('demanda_fila', models.TextField(blank=True, db_column='Demanda.Fila', null=True)),
                ('demanda_prioridade', models.TextField(blank=True, db_column='Demanda.Prioridade', null=True)),
                ('demanda_canal', models.TextField(blank=True, db_column='Demanda.Canal', null=True)),
                ('demanda_tipo', models.TextField(blank=True, db_column='Demanda.Tipo', null=True)),
                ('demanda_data_criação', models.DateTimeField(blank=True, db_column='Demanda.Data Criação', null=True)),
                ('demanda_prazo', models.DateTimeField(blank=True, db_column='Demanda.Prazo', null=True)),
                ('demanda_prazo_sugerido', models.DateTimeField(blank=True, db_column='Demanda.Prazo Sugerido', null=True)),
                ('demanda_data_da_resposta', models.DateTimeField(blank=True, db_column='Demanda.Data da Resposta', null=True)),
                ('demanda_tempo_em_aberto', models.IntegerField(blank=True, db_column='Demanda.Tempo em Aberto', null=True)),
                ('demanda_tempo_em_aberto_em_minutos', models.IntegerField(blank=True, db_column='Demanda.Tempo em Aberto em Minutos', null=True)),
                ('demanda_tempo_de_trabalho', models.IntegerField(blank=True, db_column='Demanda.Tempo de Trabalho', null=True)),
                ('demanda_titulo', models.TextField(blank=True, db_column='Demanda.Titulo', null=True)),
                ('demanda_data_da_atualização', models.DateTimeField(blank=True, db_column='Demanda.Data da Atualização', null=True)),
                ('demanda_status', models.TextField(blank=True, db_column='Demanda.Status', null=True)),
                ('demanda_forma_de_recebimento', models.TextField(blank=True, db_column='Demanda.Forma de Recebimento', null=True)),
                ('demanda_orgão_interessado', models.TextField(blank=True, db_column='Demanda.Orgão Interessado', null=True)),
                ('demanda_resultado_do_atendimento', models.TextField(blank=True, db_column='Demanda.Resultado do Atendimento', null=True)),
                ('iddemandante', models.ForeignKey(db_column='IdDemandante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.PrismaDemandante')),
            ],
        ),
        migrations.CreateModel(
            name='PrismaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macrotema', models.TextField(blank=True, db_column='Macrotema', null=True)),
                ('tema', models.TextField(blank=True, db_column='Tema', null=True)),
                ('subtema', models.TextField(blank=True, db_column='Subtema', null=True)),
                ('categoria_posicionamento', models.TextField(blank=True, db_column='Categoria.Posicionamento', null=True)),
                ('categoria_tema_proposição', models.TextField(blank=True, db_column='Categoria.Tema Proposição', null=True)),
                ('iddemanda', models.ForeignKey(db_column='IdDemanda', on_delete=django.db.models.deletion.DO_NOTHING, to='app.PrismaDemanda')),
            ],
        ),
        migrations.CreateModel(
            name='PrismaAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto_nome', models.TextField(blank=True, db_column='Assunto.Nome', null=True)),
                ('assunto_iddemanda', models.ForeignKey(db_column='Assunto.IdDemanda', on_delete=django.db.models.deletion.DO_NOTHING, to='app.PrismaDemanda')),
            ],
        ),
        migrations.CreateModel(
            name='PortalComentarioPosicionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('usuario_nome', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
                ('favor', models.SmallIntegerField()),
                ('id_comentario', models.ForeignKey(db_column='id_comentario', on_delete=django.db.models.deletion.DO_NOTHING, to='app.PortalComentario')),
            ],
            options={
                'unique_together': {('id_comentario', 'usuario_id')},
            },
        ),
    ]
