# Generated by Django 3.0.6 on 2020-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_portalcomentario_portalcomentarioposicionamento_prismaassunto_prismacategoria_prismademanda_prismade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalcomentarioposicionamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prismaassunto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prismacategoria',
            name='id',
        ),
        migrations.AddField(
            model_name='portalcomentarioposicionamento',
            name='local_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prismaassunto',
            name='local_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prismacategoria',
            name='local_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
