# Generated by Django 3.0.6 on 2020-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201216_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prismademandante',
            name='demandante_data_cadastro',
            field=models.DateTimeField(db_column='Demandante.Data Cadastro', null=True),
        ),
    ]
