# Generated by Django 3.0.6 on 2020-12-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201216_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('atendimentos_telefone', models.IntegerField(default=0)),
                ('atendimentos_autosservico', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='noticiapageviews',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='noticiapageviews',
            name='pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposicaofichapageviews',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='noticiapageviews',
            unique_together={('noticia', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='proposicaofichapageviews',
            unique_together={('proposicao', 'date')},
        ),
        migrations.CreateModel(
            name='NoticiaAggregated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('pageviews', models.IntegerField(default=0)),
                ('portal_comments', models.IntegerField(default=0)),
                ('portal_comments_unchecked', models.IntegerField(default=0)),
                ('portal_comments_authorized', models.IntegerField(default=0)),
                ('portal_comments_unauthorized', models.IntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Noticia')),
            ],
        ),
    ]
