# Generated by Django 3.0.6 on 2021-02-03 15:03

from django.db import migrations, models
import django.db.models.deletion
from app.dataloader.common import batch_qs

def migrate_tema_principal(apps, schema_editor):
    Noticia = apps.get_model('app', 'Noticia')
    NoticiaTema = apps.get_model('app', 'NoticiaTema')

    for _, _, _, qs in batch_qs(Noticia.objects.all(), batch_size=1000):
        for noticia in qs:
            try:
                tema_id = noticia.raw_data['tema_principal']['id']
                tema_titulo = noticia.raw_data['tema_principal']['titulo']
            except KeyError:
                tema_id = None
            
            if tema_id:
                try:
                    noticia_tema = NoticiaTema.objects.get(pk=tema_id)
                except NoticiaTema.DoesNotExist:
                    noticia_tema = NoticiaTema.objects.create(pk=tema_id, titulo=tema_titulo)
                noticia.tema_principal = noticia_tema
                noticia.save()

def migrate_tags(apps, schema_editor):
    Noticia = apps.get_model('app', 'Noticia')
    NoticiaTag = apps.get_model('app', 'NoticiaTag')

    for _, _, _, qs in batch_qs(Noticia.objects.all(), batch_size=1000):
        for noticia in qs:
            try:
                tags_conteudo = noticia.raw_data['tags_conteudo']
            except KeyError:
                tags_conteudo = []
                
            for tag in tags_conteudo:
                tag_id = tag['id']
                tag_nome = tag['nome']
                tag_slug = tag['slug']

                try:
                    noticia_tag = NoticiaTag.objects.get(pk=tag_id)
                except NoticiaTag.DoesNotExist:
                    noticia_tag = NoticiaTag.objects.create(pk=tag_id, nome=tag_nome, slug=tag_slug)
                noticia.tags_conteudo.add(noticia_tag)
            noticia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210104_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags_conteudo',
            field=models.ManyToManyField(to='app.NoticiaTag'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tema_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NoticiaTema'),
        ),
        migrations.RunPython(migrate_tema_principal),
        migrations.RunPython(migrate_tags),
    ]
