# Generated by Django 3.1.6 on 2021-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210203_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='prismacategoria',
            name='categoria_debate_nacional',
            field=models.TextField(blank=True, db_column='Categoria.Debate Nacional', null=True),
        ),
        migrations.AddField(
            model_name='prismacategoria',
            name='categoria_deputado',
            field=models.TextField(blank=True, db_column='Categoria.Deputado', null=True),
        ),
        migrations.AddField(
            model_name='prismacategoria',
            name='categoria_legislativo',
            field=models.TextField(blank=True, db_column='Categoria.Legislativo', null=True),
        ),
        migrations.AddField(
            model_name='prismacategoria',
            name='categoria_legislação',
            field=models.TextField(blank=True, db_column='Categoria.Legislação', null=True),
        ),
        migrations.AddField(
            model_name='prismacategoria',
            name='categoria_orcamento',
            field=models.TextField(blank=True, db_column='Categoria.Orçamento', null=True),
        ),
    ]
